#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export FLTK_BACKEND=hybrid

# Check if PulseAudio is running
if command -v pulseaudio >/dev/null 2>&1; then
    if pulseaudio --check; then
        export PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    fi
fi

# Launch the application
exec "${HERE}/usr/bin/chat_client" "$@"
